@extends('layouts.main-repertoire2020')
@section('content')

<div class="container mt-4">
  <div class="row">


   <div class="col-md-4 pb-6">

      <div class="">
              <img src="../resources/img/littoral2020/Gahoui/img1.PNG"  width="200PX"    alt=""><br>
              <small style="float:left; ">Esclavage</small>
      </div>
 
    
   </div>

    <div class="col-md-4 pb-6">

      <div class="">
              <img src="../resources/img/littoral2020/Gahoui/img2.PNG"  width="200PX"    alt=""><br>
              <small style="float:left; ">Je regarde là où je vaisSérie Enfants soldats</small>
      </div>

    </div>
    <div class="col-md-4 pb-6">

      <div class="">
              <img src="../resources/img/littoral2020/Gahoui/img3.PNG"  width="200PX"    alt=""><br>
              <small style="float:left; ">Hommage aux chaussures</small>
      </div>

    </div>

    
  </div>
</div>

<div class=" identités pt-4 mr-4 ml-4">

  <div class=" identities">
    <h2>Gahoui</h2>
    <small></small>
  </div>
  <div class="">
    <img src="../resources/img/littoral2020/Gahoui/auteur.PNG" alt="" style="">
  </div>

</div>

<div class="container  artiste-content" >
  <div class="row">

    <div class="col-md-6 ">
            <p>Samson  Gahowi  a  choisi  d’être  libre,  il  vit  en  bord  de  mer  dans un abri improvisé et corollaire de cette liberté, il récu-père ce que la mer rejette pour faire des sculptures pleines de  poésie  et  d’ingéniosité.  Masques  ou  installations,  Le  sage,  Hommage  aux  chaussures,  L’évolution  de  la  lumière,  et  les  quelques  scènes  bibliques  sont  composées  avec  des  « tapettes » (chaussures de plage), des ampoules, des vieux vêtements,  des  boîtes  de  conserves.  Sensible  au  regard qu’on  pose  sur  le  monde,  au  peu  de  tendresse  qu’on  dis-pense autour de soi, il rend hommage aux petites choses de la vie. La récupération, on le sait, rien de nouveau, pourtant elle prend ici une dimension nécessaire. A travers ses actes engagés, Gaoui « photographie » la pollution engendrée par la consommation et tente de secouer l’immobilisme des diri-geants et de la population. Il rend par là une certaine beauté à ces objets devenus inutiles puisque supposés inutilisables. F.B.
            </p>


    </div>
    <hr>
    <div class="col-md-6 artiste-content-traduction">
            <p>Samson  Gahowi  has  chosen  to  be  free,  he  lives  by  the  sea  in an improvised shelter and as a corollary of this freedom, he recovers what the sea rejects to make sculptures filled with  poetry  and  ingenuity.  Masks  or  installations,  The  wise  man, Homage to shoes, The evolution of light, and the few biblical scenes are composed with ‘‘fags’’ (beach shoes), light bulbs, old clothes, cans. Sensitive to the way we look at the world, to the little tenderness we give out around us, he pays homage to the little things in life. Recuperation, as we know, is nothing new, yet here it takes on a necessary dimension. Through  his  committed  acts,  Gaoui  ‘‘photographs’’  the  pol-lution generated by consumption and tries to shake up the immobility  of  leaders  and  the  population.  By  doing  so,  he  restores  certain  beauty  to  these  objects  that  have  become  useless since they are supposedly unusable. F.B.
            </p>
    </div>
    
  </div>
</div>
<hr>

<small class="contact">CONTACT</small><br>
<small>Tél : +229 66 32 67 62</small><br>
<small>E-mail : s.gahoui@yahoo.fr</small><br>


@endsection
