@extends('layouts.main-repertoire2020')
@section('content')

<div class="container mt-4">
  <div class="row">


   <div class="col-md-3 pb-6">

      <div class="">
              <img src="../resources/img/littoral2020/Makef/img1.PNG"  width="110PX"    alt=""><br>
              <small style="float:left; ">N’honu É sanu</small>
      </div>
    
   </div>

   <div class="col-md-3 pb-6">

      <div class="">
              <img src="../resources/img/littoral2020/Makef/img2.PNG"  width="110PX"    alt=""><br>
              <small style="float:left; ">Bienvenue T</small>
      </div>
      
   </div>

   <div class="col-md-3 pb-6">

    <div class="">
            <img src="../resources/img/littoral2020/Makef/img3.PNG"  width="110PX"    alt=""><br>
            <small style="float:left; ">Le Père Noël </small>
    </div>

  </div>

  <div class="col-md-3 pb-6">

    <div class="">
            <img src="../resources/img/littoral2020/Makef/img4.PNG"  width="110PX"    alt=""><br>
            <small style="float:left; ">Le coq a un propriétaire</small>
    </div>

    </div>

    
  </div>
</div>

<div class=" identités pt-4 mr-4 ml-4">

  <div class=" identities">
    <h2>Makef</h2>
    <small>Né en 1967</small>
  </div>
  <div class="">
    <img src="../resources/img/littoral2020/Makef/auteur.PNG" alt="" style="">
  </div>

</div>

<div class="container  artiste-content" >
  <div class="row">

    <div class="col-md-6 ">
            <p>Fulbert  Enagnon  Makoutodé  alias  Makef  aurait  rencontré  l’art  à  l’école  primaire  par  l’entremise  de  son  instituteur.  Il  se  forme  auprès  du  peintre  béninois  Amédée  Magou  et  du  français François Zenner chez qui il développe sa prédilec-tion pour le figuratif qui n’est pas sans être influencé par Magou et le cubisme. En effet, il reprend  à son compte un style qui aurait été inspiré, dit-on, à Picasso, Braque et Léger par la statuaire et les masques africains. Une nouvelle diges-tion, peut-être plus complète de cet art africain désigné très souvent à tort comme un art primitif. Le style «néo-cubiste» dont il se fait l’écho lui sert à montrer une société béninoise fragmentée  mais  qui  cherche  à  se  reconstruire.  Les  cloi-sons et les compartiments qui apparaissent dans ses toiles ne  sont  pas  hermétiques,  ils  communiquent  entre  eux,  de  sorte  que  les  blessures  générées  par  la  déstructuration  de  la  société  puissent  être  suturées  par  l’intermédiaire  de  la  peinture.  Les  thèmes  abordés  par  l’artiste  sont  éclectiques,  mais ils touchent au quotidien des Béninois et questionnent le sens même de l’existence, de la vie. Les dessins de sa série «Mes nuits insomniaques» apparaissent comme des instan-tanés de nos actions que nous n’aurions pas forcément aimé afficher au grand jour. Les images de Makef sont autant de miroirs sur notre être intérieur, qui nous rappellent combien la dualité qui nous fonde peut être prégnante. D.H.
            </p>


    </div>
    <hr>
    <div class="col-md-6 artiste-content-traduction">
            <p>Fulbert  Enagnon  Makoutodé  alias  Makef  is said to have encountered art in primary school  through  his  teacher.  He  trained  with  the  Beninese  painter  Amédée  Magou  and  the  Frenchman  François Zenner, with whom he developed a predilection for the figurative, which was not without being influenced by Magou and cubism. He indeed took over a style that is said to have been inspired by Picasso, Braque and Léger through statuary  and  African  masks.  A  new,  perhaps  more  complete  digestion of this African art, often wrongfully referred to as primitive  art.  The  «neo-cubist»  style  that  it  echoes  serves  to  show  a  Beninese  society  that  is  fragmented  but  is  see-king to rebuild itself. The partitions and compartments that appear in his canvases are not hermetic, they communicate with each other, so that the wounds generated by the des-tructuring  of  society  can  be  sutured  through  painting.  The  themes tackled by the artist are eclectic, but they touch the Beninese people’s everyday life and question the very mea-ning  of  existence,  of  life  itself.  The  drawings  in  his  series  ‘‘Mes  nuits  insomniaques’’,  My  insomniac  nights,  appear  as  snapshots of our actions that we would not necessarily have liked  to  display  in  broad  daylight.  Makef’s  images  are  as  many  mirrors  of  our  inner  being,  reminding  us  how  much  the duality that underlies us can be powerful. D.H.
            </p>
    </div>
    
  </div>
</div>
<hr>

<small class="contact">CONTACT</small><br>
<small>Tél : +229 95 75 48 72 / 62 01 28 18 </small><br>
<small>E-mail : makef67@yahoo.fr / makefenagnon@gmail.com</small><br>



@endsection
